# Generated by Django 2.2.4 on 2019-08-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='longcode',
            field=models.CharField(default='india', max_length=500),
            preserve_default=False,
        ),
    ]
